### ISSUE TITLE
Do you have an example of how to configure vs code or webstorm to launch your example from within the IDE?

### ISSUE THREAD

**Issue by silverfox1948** [b091/ts-skeleton#10]
I'd like to use Webstorm or VS Code to run your example. However, I can't quite figure out how to modify the configuration to run your "gulp serve" task.

Do  you have an example you can share? (VS Code preferred ...)

Or even Visual Studio Community with the node.js tools installed ...

**Comment by b091** [comment]
I use WebStrom, is below gifs is what you're looking for ?

![ws-gulp-2](https://cloud.githubusercontent.com/assets/228489/11567069/80269526-99e5-11e5-9fdc-94dc1c74d4b6.gif)
![ws-gulp](https://cloud.githubusercontent.com/assets/228489/11567070/804a2054-99e5-11e5-9b4f-996ac753c7af.gif)
