### ISSUE TITLE
Internal modules across files not working !?

### ISSUE THREAD

**Issue by Xample** [b091/ts-skeleton#11]
I have problems using internal modules across multiple files.
It seems to be very similar to the one described here:
http://stackoverflow.com/questions/31041311/typescript-internal-module-across-multiple-files-in-nodejs

Basically I tried to reproduce the example here:
http://www.typescriptlang.org/Handbook#modules-splitting-across-files

But it seems that:
```javascript
/// <reference path="Validation.ts" />
/// <reference path="LettersOnlyValidator.ts" />
/// <reference path="ZipCodeValidator.ts" />
```

Is only useful for the editor, once the code compiled, looking at the .js file nothing was actually imported and I get an "Uncaught (in promise) Error: Validation is not defined(…)" at runtime.

My first idea is jspm is not supporting those dependencies as TSC is using the -out argument

Any idea / suggestion / solution ?

**Comment by b091** [comment]
Hi,

You shout't use internal modules. You should use external modules where directories are packages and file is module. Then you don't need to use 
```javascript
    /// <reference.....
```
Instead of this you only import what you want to use
```javascript
    import {Foo} from '../foo/Bar'
```
All modules in this repo are in external modules approach.
