### ISSUE TITLE
protractor.conf.js strange return assignment

### ISSUE THREAD

**Issue by Xample** [b091/ts-skeleton#12]
What is the purpose of this ?
```js
    //For non-angular apps (line 12)
    global.ignoreSynchronization = function () {
      return browser.ignoreSynchronization = true;
    };
```
i.e. you assign something and return it the same way. Shouldn't it be one of those ?
```js
      return browser.ignoreSynchronization;
```
or
```js
      return browser.ignoreSynchronization === true;
```

**Comment by b091** [comment]
Hi,

Good point. This is a way to make protractor not to wait for Angular to finish its work.
Actually it doesn't need to return value, and more elegant way is to do it by flag.

```
    // For non-angular apps
    global.ignoreSynchronization = function (flag) {
      browser.ignoreSynchronization = flag;
    };
```
and with it we can set it on demand in `beforeeach`

improvement is on master :)
