### ISSUE TITLE
"gulp test" not working

### ISSUE THREAD

**Issue by Xample** [b091/ts-skeleton#14]
while typing
```bash
gulp task
```
Gulp will compile the files and run the unit and e2e tests.
```js
gulp.task('test', ['compile', 'test:unit', 'test:e2e']);
```
While the e2e is served and tested correctly, here is what I get from the unit testing:
```bash
[15:27:31] Starting 'compile:test'...
[15:27:31] Finished 'clean:src' after 2.48 s
[15:27:31] Starting 'compile:src'...
WARNING - pattern /Users/me/ts-skeleton/test/e2e/initialization.spec.js did not match any files.
[launcher] Process exited with error code 1
…
```
I need to manually run the following:
```bash
gulp compile
gulp test:unit
```
I've found one possible related issues: https://github.com/angular/protractor/issues/2551
But the version included is "protractor": "~3.0.0" so…

any idea / workaround ?

**Comment by b091** [comment]
Hi,

actually i have no clue why this is happen to you.
All tasks in 'test' group are running with `runSequence` so they should run synchronously.
Anyway the file `test/e2e/initialization.spec.js` does not take part in compilation nor "cleaning", so it should always be available in its path

I've cloned clear repo. I have no idea, how to fix your issue. I cannot reproduce it :(

Regards


![gulp-test](https://cloud.githubusercontent.com/assets/228489/12785186/8d1d270a-ca8b-11e5-8d79-dda9518ec1bb.gif)

**Comment by Xample** [comment]
Mmm… I never had the same behaviour, give me few time to double check and possibly find the issue.
