### ISSUE TITLE
Controller testing

### ISSUE THREAD

**Issue by kobvel** [b091/ts-skeleton#15]
Hello, Thank you for great starting point of NG+ TS.

I am trying to test controller, but I have no access to `inject` function in `beforEach` construction inside spec file. Could you please create sample test for internal functions of controller?

**Comment by b091** [comment]
Hi,

I'll create this sample (i even started), but I need to get some time for that.

Regards

**Comment by primavera133** [comment]
Would be much appreciated with some more elaborate examples of unit testing; a Service, a Controller, etc.

**Comment by b091** [comment]
I've just added very simple test of Service and Controller. 
You can find it here: [Controller](https://github.com/b091/ts-skeleton/blob/master/test/unit/module/auth/LoginCtrl.spec.ts), [Service](https://github.com/b091/ts-skeleton/blob/master/test/unit/module/story/StoryService.spec.ts)

Is this enough for you guys or you need some more complex tests?

**Comment by primavera133** [comment]
Cheers, very helpful!
