### ISSUE TITLE
Even more future proof with decorators

### ISSUE THREAD

**Issue by Successful** [b091/ts-skeleton#18]
Just a thought, i think this project should be more future proof if we implemented decorators?

**Se this script for reference:**
[Decorators.js](https://github.com/davinkevin/Podcast-Server/blob/master/www/app/decorators.js)

**Update**

Found this: https://github.com/ngUpgraders/ng-forward

**Comment by Successful** [comment]
Started with this and need some help to make it work:

https://github.com/ngUpgraders/ng-forward/issues/148

**Comment by b091** [comment]
Hi, 

I'll try to look into this but now I'm running out of free time.
That's why I labeled it with 'help wanted' ;)

Regards
