### ISSUE TITLE
gulp build not working anymore

### ISSUE THREAD

**Issue by Xample** [b091/ts-skeleton#19]
We took the last seed of the project and tried to run
```bash
gulp build
```
Unfortunately this leads us to:
```bash
Build Failed [Error: ENOENT: no such file or directory, open '/Users/xample/Documents/Icflix/SmartTV/TEST/ts-skeleton/src/index']
```

The workaround was to remove the line 10 on the jspm.conf.js
```js
  paths: {
    "github:*": "vendor/jspm_packages/github/*",
    "npm:*": "vendor/jspm_packages/npm/*",
    "app": "src/index" // <- remove this line
  },
```
…and to hardcode the module main file into build-dist.js
```js
var mainfile = "src/index.js"
return builder.buildStatic(mainfile, outFile, buildConfig);
```
 
I tried to take older seeds, npm install, jspm install but the problem persisted. Another coworker faced the same issue. Here below are the globals:

```bash
mbp:src example$ gulp --version
[17:51:17] CLI version 3.9.1
[17:51:17] Local version 3.9.1

mbp:src example$ tsc --version
message TS6029: Version 1.7.5

mbp:src example$ tsd --version
>> tsd 0.6.5

mbp:src example$ jspm --version
0.16.27

```

**Comment by b091** [comment]
Hi, 

it's because jspm downloads never version of systems-builder.

it's fixed on master now.

Regards

**Comment by hnb2** [comment]
Now that's a quick fix ! Thanks a lot, we've been scratching our head for a long time.

**Comment by Xample** [comment]
Excellent, will fix my workaround, thanks!
