### ISSUE TITLE
Self executing bundle without system.js

### ISSUE THREAD

**Issue by DannyMoerkerke** [b091/ts-skeleton#6]
Is it possible to build a self-executing bundle that I can include with a script tag without having to include system.js, just like jspm.bundleSFX?
I've tried setting "format" in config to "system", which gives me:

[Error: ENOENT: no such file or directory, open '/Users/danny/web/ts-skeleton/node_modules/jspm/node_modules/systemjs-builder/templates/sfx-system.js'

I also tried "esm" as format but then the browser console gives me:
Uncaught ReferenceError: define is not defined.

In both cases I replaced  System.import('./src/index'); with <script src="src/index.js"></script>

Apparently this does not work so I was hoping you could help me with this.
Thanks for an awesome project!

**Comment by DannyMoerkerke** [comment]
Never mind, I just noticed the index.html in the /dist folder with everything I was looking for.
Thanks agian!

**Comment by Xample** [comment]
@DannyMoerkerke 
How did you fixed this ? I just:
```bash
gulp build
gulp serve:dist
```
and got the same error:
```js
Uncaught ReferenceError: define is not defined
```

**Comment by b091** [comment]
Hi, 

this problem should not occur anymore. I've changed default dist format from `amd` to `global`

it's on master now.

## build-dist.js

from :
```javascript
  const buildConfig = {
      format: 'amd',
      minify: true,
      sourceMaps: true
    };
```

to :
```javascript
  const buildConfig = {
      format: 'global',
      minify: true,
      sourceMaps: true
    };
```

**Comment by Xample** [comment]
Yes fixed! thank you

**Comment by DannyMoerkerke** [comment]
@Xample my problem was that I hadn't compiled to javascript yet, I am just starting Typescript and I assumed I could bundle straight away ;-)
